// Curated static skills list for autocomplete.
// Sorted case-insensitively via localeCompare. ~200 entries covering software
// engineering, design, data science, product, marketing, operations, and finance.
export const SKILLS: string[] = [
  "A/B Testing",
  "Accessibility (WCAG)",
  "Accounting",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Photoshop",
  "Adobe XD",
  "Agile",
  "Amazon Web Services (AWS)",
  "Angular",
  "Ansible",
  "Apache Kafka",
  "Apache Spark",
  "API Design",
  "API Testing",
  "ArgoCD",
  "Artificial Intelligence",
  "Assembly",
  "Astro",
  "Attention to Detail",
  "Auditing",
  "Authentication & Authorization",
  "AutoCAD",
  "Automation Testing",
  "Azure",
  "Bash Scripting",
  "BigQuery",
  "Brand Strategy",
  "Budget Management",
  "Business Analysis",
  "Business Development",
  "Business Intelligence",
  "C",
  "C#",
  "C++",
  "Canva",
  "Change Management",
  "CI/CD",
  "Cloud Architecture",
  "Cloud Computing",
  "Coaching",
  "Communication",
  "Competitive Analysis",
  "Content Marketing",
  "Content Strategy",
  "CRM",
  "Cross-functional Collaboration",
  "CSS",
  "Customer Experience",
  "Customer Research",
  "Customer Success",
  "Cypress",
  "D3.js",
  "Data Analysis",
  "Data Engineering",
  "Data Modeling",
  "Data Pipeline",
  "Data Science",
  "Data Visualization",
  "Database Administration",
  "dbt",
  "Deep Learning",
  "Design Systems",
  "DevOps",
  "Django",
  "Docker",
  "Drizzle ORM",
  "Elasticsearch",
  "Elixir",
  "Email Marketing",
  "Emotional Intelligence",
  "Engineering Management",
  "ETL",
  "Event-Driven Architecture",
  "FastAPI",
  "Fastify",
  "Figma",
  "Finance",
  "Financial Analysis",
  "Financial Modeling",
  "Flask",
  "Flutter",
  "Forecasting",
  "Frontend Development",
  "Full-Stack Development",
  "Functional Programming",
  "Git",
  "GitHub Actions",
  "Go (Golang)",
  "Google Analytics",
  "Google Cloud Platform (GCP)",
  "GraphQL",
  "Growth Hacking",
  "gRPC",
  "Hadoop",
  "Helm",
  "HTML",
  "HTTP / REST",
  "Information Architecture",
  "Infrastructure as Code",
  "Interaction Design",
  "iOS Development",
  "Java",
  "JavaScript",
  "Jenkins",
  "JIRA",
  "Julia",
  "Jupyter Notebooks",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Leadership",
  "LLM Engineering",
  "Machine Learning",
  "Management",
  "Marketing Analytics",
  "Marketing Automation",
  "MATLAB",
  "Mentoring",
  "Microservices",
  "Mobile Development",
  "MongoDB",
  "MySQL",
  "Natural Language Processing",
  "Nest.js",
  "Networking",
  "Next.js",
  "Nginx",
  "NLP",
  "Node.js",
  "NoSQL",
  "NumPy",
  "Object-Oriented Programming",
  "OpenAI API",
  "Operations",
  "Oracle",
  "Pandas",
  "Payment Systems",
  "Performance Optimization",
  "Playwright",
  "PostgreSQL",
  "Prisma",
  "Problem Solving",
  "Product Management",
  "Product Marketing",
  "Product Strategy",
  "Project Management",
  "Prometheus",
  "Prototyping",
  "Python",
  "PyTorch",
  "R",
  "React",
  "React Native",
  "Redis",
  "Remix",
  "Requirements Gathering",
  "Responsive Design",
  "Risk Management",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "Salesforce",
  "Scala",
  "Scrum",
  "Search Engine Optimization (SEO)",
  "Security Engineering",
  "Serverless",
  "Service Mesh",
  "Sketch",
  "Snowflake",
  "Social Media Marketing",
  "Software Architecture",
  "SQL",
  "Stakeholder Management",
  "Statistical Analysis",
  "Stripe",
  "Supply Chain",
  "Svelte",
  "Swift",
  "System Design",
  "Tableau",
  "Tailwind CSS",
  "Team Leadership",
  "Technical Writing",
  "Terraform",
  "Testing",
  "Time Series Analysis",
  "tRPC",
  "TypeScript",
  "UI Design",
  "Unit Testing",
  "User Research",
  "UX Design",
  "UX Writing",
  "Venture Capital",
  "Visual Design",
  "Vue.js",
  "Web3",
  "WebAssembly",
  "Webpack",
  "WebSockets",
  "WordPress",
  "Writing",
  "Zod",
]
